name: Westpac_Assets
description: Exchange Rate Table and portfolio_to_GL tables for Westpac Demo
version: '1.1'
author: nathan+westpac@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: westpacassets
  parentArtefactID: pocwestpac
  buildSystem: wheel
  author: null
  createdAt: '2024-05-13 20:25:43'
pipelines:
  pipelines/ExchangeRateTable:
    name: ExchangeRateTable
    description: ''
    author: nathan+westpac@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-13 20:25:43'
    datasets:
      inputs:
      - datasets/ExchangeRateTable
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/PortfolioToGLTable:
    name: PortfolioToGLTable
    description: ''
    author: nathan+westpac@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-13 20:26:52'
    datasets:
      inputs:
      - datasets/PortfolioToGLTable
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/convert_int_to_date:
    name: convert_int_to_date
    description: ''
    author: nathan+westpac@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-05-14 01:43:40'
    datasets:
      inputs: []
      outputs: []
    subgraphs:
    - subgraphs/convert_int_to_date
    dependencies: {}
datasets:
  datasets/ExchangeRateTable:
    name: ExchangeRateTable
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-13 20:26:33'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: Database
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-13 20:26:33'
  datasets/PortfolioToGLTable:
    name: PortfolioToGLTable
    description: ''
    author: nathan+westpac@prophecy.io
    createdAt: '2024-05-13 20:27:51'
    mode: batch
    physicalDatasets:
      Sales-eng:
        fabricId: 11613
        datasetType: Database
        description: ''
        author: nathan+westpac@prophecy.io
        createdAt: '2024-05-13 20:27:51'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-13 20:25:43'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs:
  subgraphs/convert_int_to_date:
    name: convert_int_to_date
    description: Converts Integer-formatted dates to Date Types
    author: nathan+westpac@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2024-05-14 01:52:43'
sqlModels: {}
sqlSnapshots: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-05-13T20:29:06.996187Z'
  name: plibMaven
  version: 7.1.95
  id: '1594390890'
  createdAt: '2024-05-13T20:29:06.99608Z'
- type: plibPypi
  modifiedAt: '2024-05-13T20:29:06.996302Z'
  name: plibPypi
  version: 1.8.15
  id: '1811856507'
  createdAt: '2024-05-13T20:29:06.996225Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.12
    isDefault: true
    author: null
    createdAt: '2024-05-13 20:25:34'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-05-13 20:25:34'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
